[functions]
  # this is where "Netlify can find your function sources, including background functions. 
  # Netlify will access this directory during every deploy, zipping and deploying each supported code file as a function"
  directory = "serverLambda/lambdaFunctions/"

[build]
  command = "npm run build"  # this gets run in production to do the build
  publish = "client/build" # directory where deploy-ready HTML files etc are. THis value can be set in the UI also, but this entry will override it 

[dev]
  publish = "client/public" # The path to your static content folder
  framework = "create-react-app"