# root netlify.toml
[build]
  command = "npm run build"
  # functions = "server/lambda" # netlify dev uses this directory to scaffold and serve your functions
  # publish = "client/build" # directory where deploy-ready HTML files etc are. Don't seem to need to specify this as it is set in the UI 

# note: each of these fields are OPTIONAL, with an exception that when you're specifying "command" and "port", you must specify framework = "#custom"
[dev]
  command = "npm run dev" # Command to start your dev server
  targetPort = 5000 # The port for your application server, framework or site generator
  framework = "#custom"
  publish = "client/public" # The path to your static content folder
  # jwtRolePath = "app_metadata.authorization.roles" # Object path we should look for role values for JWT based redirects
  autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser