# /server netlify.toml
[build]
  functions = "server/lambda" # netlify dev uses this directory to scaffold and serve your functions
  
# note: each of these fields are OPTIONAL, with an exception that when you're specifying "command" and "port", you must specify framework = "#custom"
[dev]
  targetPort = 5000 # The port for your application server, framework or site generator
  framework = "#custom"
  autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser