export const FETCHED_SHEET = 'fetched_sheet';
export const UPDATE_EDITOR = 'update_editor'; // TODO change to UPDATED_EDITOR
export const UPDATE_CELL_BEING_EDITED = 'update_cell_being_edited'; // TODO UPDATED_CELL_BEING_EDITED
export const UPDATED_CELL_ = 'updated_cell_';
export const CELL_ = 'cell_';
export const UPDATED_CELL_KEYS = 'updated_cell_keys';
export const SET_EDITOR_REF = 'set_editor_ref';
export const UPDATE_TITLE = 'update_title'; // TODO UPDATED_TITLE
export const SET_EDITING_TITLE = 'set_editing_title';
