const DEFAULT_ROWS = 6;
const DEFAULT_COLUMNS = 6;
const DEFAULT_TITLE = 'My Deep Deep Sheet';
const DEFAULT_SUMMARY_CELL = { row: 0, column: 0 };
const AUTH_PROVIDER_FACEBOOK = 1;
const AUTH_PROVIDER_GOOGLE = 2;

module.exports = {
   DEFAULT_ROWS,
   DEFAULT_COLUMNS,
   DEFAULT_TITLE,
   DEFAULT_SUMMARY_CELL,
   AUTH_PROVIDER_GOOGLE,
   AUTH_PROVIDER_FACEBOOK,
};
